create extension if not exists pgcrypto;

create table if not exists public.episodes (
  id uuid primary key default gen_random_uuid(),
  source_url text not null unique,
  feed_url text not null,
  title text not null,
  audio_url text not null,
  duration_seconds numeric not null default 0,
  source_language text not null default 'und',
  artwork_url text,
  transcript_source text not null check (transcript_source in ('official', 'generated')),
  created_at timestamptz not null default now()
);

create table if not exists public.transcript_segments (
  id bigint generated by default as identity primary key,
  episode_id uuid not null references public.episodes(id) on delete cascade,
  sentence_number integer not null,
  start_time_ms integer not null check (start_time_ms >= 0),
  end_time_ms integer not null check (end_time_ms > start_time_ms),
  original_text text not null,
  unique (episode_id, sentence_number)
);

create index if not exists transcript_segments_episode_time_idx
  on public.transcript_segments (episode_id, start_time_ms);

create table if not exists public.translations (
  id bigint generated by default as identity primary key,
  transcript_segment_id bigint not null references public.transcript_segments(id) on delete cascade,
  target_language text not null,
  translated_text text not null,
  created_at timestamptz not null default now(),
  unique (transcript_segment_id, target_language)
);

alter table public.episodes enable row level security;
alter table public.transcript_segments enable row level security;
alter table public.translations enable row level security;

-- The browser never accesses these tables directly. The server uses the service role.
